# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

xMatrix <- function(xVector, polyOrder) {
    .Call('_DCSmooth_xMatrix', PACKAGE = 'DCSmooth', xVector, polyOrder)
}

np_matrix <- function(kernFcnPtr, p, n = 500L) {
    .Call('_DCSmooth_np_matrix', PACKAGE = 'DCSmooth', kernFcnPtr, p, n)
}

m_weights <- function(npMatrix, u, drv) {
    .Call('_DCSmooth_m_weights', PACKAGE = 'DCSmooth', npMatrix, u, drv)
}

acfMatrix_quarter2 <- function(y_Mat) {
    .Call('_DCSmooth_acfMatrix_quarter2', PACKAGE = 'DCSmooth', y_Mat)
}

KRSmooth_matrix2 <- function(yMat, h, drv, kernFcnPtr) {
    .Call('_DCSmooth_KRSmooth_matrix2', PACKAGE = 'DCSmooth', yMat, h, drv, kernFcnPtr)
}

KR_dcs_const0 <- function(yMat, hVec, drvVec, kernFcnPtrX, kernFcnPtrT) {
    .Call('_DCSmooth_KR_dcs_const0', PACKAGE = 'DCSmooth', yMat, hVec, drvVec, kernFcnPtrX, kernFcnPtrT)
}

KRSmooth_matrix <- function(yMat, h, drv, kernFcnPtr) {
    .Call('_DCSmooth_KRSmooth_matrix', PACKAGE = 'DCSmooth', yMat, h, drv, kernFcnPtr)
}

KR_dcs_const1 <- function(yMat, hVec, drvVec, kernFcnPtrX, kernFcnPtrT) {
    .Call('_DCSmooth_KR_dcs_const1', PACKAGE = 'DCSmooth', yMat, hVec, drvVec, kernFcnPtrX, kernFcnPtrT)
}

weight_fcn_assign <- function(fstr) {
    .Call('_DCSmooth_weight_fcn_assign', PACKAGE = 'DCSmooth', fstr)
}

kernFkt_MW210 <- function(u, q = 1) {
    .Call('_DCSmooth_kernFkt_MW210', PACKAGE = 'DCSmooth', u, q)
}

kernFkt_MW220 <- function(uVec, q) {
    .Call('_DCSmooth_kernFkt_MW220', PACKAGE = 'DCSmooth', uVec, q)
}

kernFkt_MW320 <- function(u, q = 1) {
    .Call('_DCSmooth_kernFkt_MW320', PACKAGE = 'DCSmooth', u, q)
}

kernFkt_MW420 <- function(uVec, q) {
    .Call('_DCSmooth_kernFkt_MW420', PACKAGE = 'DCSmooth', uVec, q)
}

kernFkt_MW421 <- function(uVec, q) {
    .Call('_DCSmooth_kernFkt_MW421', PACKAGE = 'DCSmooth', uVec, q)
}

kernFkt_MW422 <- function(uVec, q) {
    .Call('_DCSmooth_kernFkt_MW422', PACKAGE = 'DCSmooth', uVec, q)
}

kernFkt_TR420 <- function(uVec, q) {
    .Call('_DCSmooth_kernFkt_TR420', PACKAGE = 'DCSmooth', uVec, q)
}

kernFkt_TR422 <- function(uVec, q) {
    .Call('_DCSmooth_kernFkt_TR422', PACKAGE = 'DCSmooth', uVec, q)
}

kernel_fcn_assign <- function(fstr) {
    .Call('_DCSmooth_kernel_fcn_assign', PACKAGE = 'DCSmooth', fstr)
}

kernel_fcn_use <- function(x, q, xpsexp) {
    .Call('_DCSmooth_kernel_fcn_use', PACKAGE = 'DCSmooth', x, q, xpsexp)
}

LPSmooth_matrix2 <- function(yMat, h, polyOrder, drv, kernFcnPtr) {
    .Call('_DCSmooth_LPSmooth_matrix2', PACKAGE = 'DCSmooth', yMat, h, polyOrder, drv, kernFcnPtr)
}

LP_dcs_const0 <- function(yMat, hVec, polyOrderVec, drvVec, kernFcnPtr_x, kernFcnPtr_t) {
    .Call('_DCSmooth_LP_dcs_const0', PACKAGE = 'DCSmooth', yMat, hVec, polyOrderVec, drvVec, kernFcnPtr_x, kernFcnPtr_t)
}

LPSmooth_matrix2_BMod <- function(yMat, h, polyOrder, drv, mu, weightFcnPtr) {
    .Call('_DCSmooth_LPSmooth_matrix2_BMod', PACKAGE = 'DCSmooth', yMat, h, polyOrder, drv, mu, weightFcnPtr)
}

LP_dcs_const0_BMod <- function(yMat, hVec, polyOrderVec, drvVec, muVec, weightFcnPtr_x, weightFcnPtr_t) {
    .Call('_DCSmooth_LP_dcs_const0_BMod', PACKAGE = 'DCSmooth', yMat, hVec, polyOrderVec, drvVec, muVec, weightFcnPtr_x, weightFcnPtr_t)
}

LPSmooth_matrix <- function(yMat, h, polyOrder, drv, kernFcnPtr) {
    .Call('_DCSmooth_LPSmooth_matrix', PACKAGE = 'DCSmooth', yMat, h, polyOrder, drv, kernFcnPtr)
}

LP_dcs_const1 <- function(yMat, hVec, polyOrderVec, drvVec, kernFcnPtr_x, kernFcnPtr_t) {
    .Call('_DCSmooth_LP_dcs_const1', PACKAGE = 'DCSmooth', yMat, hVec, polyOrderVec, drvVec, kernFcnPtr_x, kernFcnPtr_t)
}

LPSmooth_matrix_BMod <- function(yMat, h, polyOrder, drv, mu, weightFcnPtr) {
    .Call('_DCSmooth_LPSmooth_matrix_BMod', PACKAGE = 'DCSmooth', yMat, h, polyOrder, drv, mu, weightFcnPtr)
}

LP_dcs_const1_BMod <- function(yMat, hVec, polyOrderVec, drvVec, muVec, weightFcnPtr_x, weightFcnPtr_t) {
    .Call('_DCSmooth_LP_dcs_const1_BMod', PACKAGE = 'DCSmooth', yMat, hVec, polyOrderVec, drvVec, muVec, weightFcnPtr_x, weightFcnPtr_t)
}

